import * as dotenv from 'dotenv';
dotenv.config();

const  { 
    DEV_DATABASE_HOST, 
    DEV_DATABASE_PORT, 
    DEV_DATABASE_NAME, 
    DEV_API_PORT, 
    DEV_MQTT_URL, 
    DEV_MQTT_TOPIC, 
    PRODUCTION_DATABASE_HOST, 
    PRODUCTION_DATABASE_PORT, 
    PRODUCTION_DATABASE_NAME, 
    PRODUCTION_API_PORT, 
    PRODUCTION_MQTT_URL, 
    PRODUCTION_MQTT_TOPIC,
    ENVIRONMENT } = process.env;

const productionEnvironment = {
    DATABASE_HOST: PRODUCTION_DATABASE_HOST, 
    DATABASE_PORT: PRODUCTION_DATABASE_PORT, 
    DATABASE_NAME: PRODUCTION_DATABASE_NAME, 
    API_PORT: PRODUCTION_API_PORT, 
    MQTT_URL: PRODUCTION_MQTT_URL, 
    MQTT_TOPIC: PRODUCTION_MQTT_TOPIC
};
const developmentEnvironment = {
    DATABASE_HOST: DEV_DATABASE_HOST, 
    DATABASE_PORT: DEV_DATABASE_PORT, 
    DATABASE_NAME: DEV_DATABASE_NAME, 
    API_PORT: DEV_API_PORT, 
    MQTT_URL: DEV_MQTT_URL, 
    MQTT_TOPIC: DEV_MQTT_TOPIC, 
};

export default ENVIRONMENT == 'production' ? productionEnvironment : developmentEnvironment;